#!/bin/bash

cargo build --release
toml=$(cat Cargo.toml) 
pattern="\"([0-9]{2})\""
for word in $toml; do
  [[ $word =~ $pattern ]]
  if [[ ${BASH_REMATCH[1]} ]]; then
    prg="${BASH_REMATCH[1]}"
    echo "Problem $prg":
    ./target/release/$prg
  fi
done